############ DO NOT CHANGE THESE #################
INCDIR:=../:../../common_bsv:../../axi4:../../apb:../../axi4_lite:
MASTERS=2
SLAVES=5
############# User changes to be done below #################
TOP_MODULE:=mkTb
TOP_DIR:=./
TOP_FILE:=latency_test_axi2axil.bsv

