############ DO NOT CHANGE THESE #################
INCDIR:=../:../../common_bsv
MASTERS=2
SLAVES=5
############# User changes to be done below #################
TOP_MODULE:=mkTb
TOP_DIR:=./
TOP_FILE:=latency_test.bsv

